media:
  input: "assets/images"
  output: "/assets/images"

content:
  - name: "projects"
    label: "Projects"
    type: "collection"
    path: "content/projects"
    format: "json"
    fields:
      - name: "title"
        label: "Project Name"
        type: "string"
        required: true

      - name: "version"
        label: "Latest Version"
        type: "string"
        required: true

      - name: "download_url1"
        label: "Download Link Ubuntu"
        type: "string"
        
      - name: "download_url2"
        label: "Download Link MacOS"
        type: "string"
     
      - name: "download_url3"
        label: "Download Link Windows"
        type: "string"

      - name: "description"
        label: "Short Description"
        type: "text"

      - name: "image"
        label: "Project Image"
        type: "image"